FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

WORKDIR /app

# dot means WORKDIR, could be replaced by /app
COPY ./app/requirements.txt .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt 

COPY ./app /app

ENV PYTHONPATH=/app